include: package:lints/recommended.yaml
plugins:
  genesis_lint:
    path: packages/lint
analyzer:
  exclude:
    - packages/lint/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
linter:
  rules:
    - prefer_single_quotes
    - sort_pub_dependencies
    - unawaited_futures
    - avoid_print
