// GENERATED — do not edit.
// Generated by genesis_taxonomy from catalog 'fixture' v0.1.0.
//
// Typed factory registry: wire type name -> Seed factory.
// Construction-time validation (unknown type, missing or
// mistyped prop, unknown prop, children on a leaf) throws
// structured TaxonomyExceptions; nothing outside this file
// hardcodes component type names.

import 'package:genesis_taxonomy/genesis_taxonomy.dart';

import 'fixture_seeds.dart';

/// Typed factory registry for catalog 'fixture' v0.1.0.
final ComponentRegistry componentRegistry = ComponentRegistry(
  catalogName: 'fixture',
  catalogVersion: '0.1.0',
  entries: {
    'gauge': RegistryEntry(
      container: false,
      knownProps: const {'label', 'value', 'scale', 'enabled', 'align'},
      build: (props, children, key) => Gauge(
        Props.string('gauge', props, 'label'),
        value: Props.number('gauge', props, 'value'),
        scale: Props.integerOr('gauge', props, 'scale', 10),
        enabled: Props.booleanOr('gauge', props, 'enabled', true),
        align: Props.enumerationOr('gauge', props, 'align', const [
          'start',
          'center',
          'end',
        ], 'start'),
        key: key,
      ),
    ),
    'label': RegistryEntry(
      container: false,
      knownProps: const {'name', 'value'},
      build: (props, children, key) => Label(
        name: Props.string('label', props, 'name'),
        value: Props.string('label', props, 'value'),
        key: key,
      ),
    ),
    'panel': RegistryEntry(
      container: true,
      knownProps: const {'name'},
      build: (props, children, key) => Panel(
        Props.string('panel', props, 'name'),
        children: children,
        key: key,
      ),
    ),
  },
);
