// Front-buffer render-to-string snapshots for the locality suite
// (trailing whitespace trimmed; compare against frontToString().trimRight()).
// Generated by tool/print_snapshots.dart and eyeballed before locking.
//
// Note the feed box is 3 rows: flow layout v1 sizes a Box from its content
// (one line + border), unlike the old fixed-rect delegate's uniform 4.

/// Frame 0: ticker at initialValue 0, static box, feed at '(none)'.
const initialSnapshot = '''
┌─ ticker ─────────────────────────────┐
│ count: 0                             │
│ square: 0                            │
└──────────────────────────────────────┘
┌─ static ─────────────────────────────┐
│ mode: idle                           │
│ uptime: n/a                          │
└──────────────────────────────────────┘
┌─ feed ───────────────────────────────┐
│ last: (none)                         │
└──────────────────────────────────────┘''';

/// After ticker events 1, 2, 3, 42, 137 and feed event 'done'.
const finalSnapshot = '''
┌─ ticker ─────────────────────────────┐
│ count: 137                           │
│ square: 18769                        │
└──────────────────────────────────────┘
┌─ static ─────────────────────────────┐
│ mode: idle                           │
│ uptime: n/a                          │
└──────────────────────────────────────┘
┌─ feed ───────────────────────────────┐
│ last: done                           │
└──────────────────────────────────────┘''';
