// Front-buffer render-to-string snapshots for the locality suite.
// Generated by tool/print_snapshots.dart and eyeballed before locking.

/// Frame 0: ticker at initialValue 0, static box, feed at '(none)'.
const initialSnapshot = '''
┌─ ticker ─────────────────────────────┐
│ count: 0                             │
│ square: 0                            │
└──────────────────────────────────────┘
┌─ static ─────────────────────────────┐
│ mode: idle                           │
│ uptime: n/a                          │
└──────────────────────────────────────┘
┌─ feed ───────────────────────────────┐
│ last: (none)                         │
│                                      │
└──────────────────────────────────────┘''';

/// After ticker events 1, 2, 3, 42, 137 and feed event 'done'.
const finalSnapshot = '''
┌─ ticker ─────────────────────────────┐
│ count: 137                           │
│ square: 18769                        │
└──────────────────────────────────────┘
┌─ static ─────────────────────────────┐
│ mode: idle                           │
│ uptime: n/a                          │
└──────────────────────────────────────┘
┌─ feed ───────────────────────────────┐
│ last: done                           │
│                                      │
└──────────────────────────────────────┘''';
