// GENERATED — do not edit.
// Generated by genesis_taxonomy from catalog 'console' v0.1.0.
//
// Typed factory registry: wire type name -> Seed factory.
// Construction-time validation (unknown type, missing or
// mistyped prop, unknown prop, children on a leaf) throws
// structured TaxonomyExceptions; nothing outside this file
// hardcodes component type names.

import 'package:genesis_console/src/counter.dart';
import 'package:genesis_taxonomy/genesis_taxonomy.dart';
import 'package:genesis_typesetting/genesis_typesetting.dart';

/// Typed factory registry for catalog 'console' v0.1.0.
final ComponentRegistry componentRegistry = ComponentRegistry(
  catalogName: 'console',
  catalogVersion: '0.1.0',
  entries: {
    'box': RegistryEntry(
      container: true,
      knownProps: const {'title'},
      build: (props, children, key) => Box(
        title: Props.string('box', props, 'title'),
        children: children,
        key: key,
      ),
    ),
    'counter': RegistryEntry(
      container: false,
      knownProps: const {'label', 'start'},
      build: (props, children, key) => Counter(
        label: Props.string('counter', props, 'label'),
        start: Props.integerOr('counter', props, 'start', 0),
        key: key,
      ),
    ),
    'text': RegistryEntry(
      container: false,
      knownProps: const {'content'},
      build: (props, children, key) =>
          Text(Props.string('text', props, 'content'), key: key),
    ),
  },
);
