// GENERATED — do not edit.
// Generated by genesis_taxonomy from catalog 'consent_fixture' v0.1.0.
//
// Typed factory registry: wire type name -> Seed factory.
// Construction-time validation (unknown type, missing or
// mistyped prop, unknown prop, children on a leaf) throws
// structured TaxonomyExceptions; nothing outside this file
// hardcodes component type names.

import 'package:genesis_perception/genesis_perception.dart';
import 'package:genesis_taxonomy/genesis_taxonomy.dart';

import 'consent_fixtures.dart';

/// Typed factory registry for catalog 'consent_fixture' v0.1.0.
final ComponentRegistry componentRegistry = ComponentRegistry(
  catalogName: 'consent_fixture',
  catalogVersion: '0.1.0',
  entries: {
    'counter': RegistryEntry(
      container: false,
      knownProps: const {'label', 'start'},
      build: (props, children, key) => Counter(
        Props.string('counter', props, 'label'),
        start: Props.integerOr('counter', props, 'start', 0),
        key: key,
      ),
    ),
    'field': RegistryEntry(
      container: false,
      knownProps: const {'name', 'value'},
      build: (props, children, key) => Field(
        Props.string('field', props, 'name'),
        Props.string('field', props, 'value'),
        key: key,
      ),
    ),
    'node': RegistryEntry(
      container: true,
      knownProps: const {'name'},
      build: (props, children, key) => Node(
        Props.string('node', props, 'name'),
        children: children,
        key: key,
      ),
    ),
  },
);
