/// Projection 1: the typed Dart factory registry.
///
/// Emits a `.g.dart` source file that instantiates a `ComponentRegistry`
/// binding the catalog's wire types to `Seed` constructors. The generated
/// file is thin wiring — all validation machinery lives in the
/// `registry_runtime.dart` library, so generated code stays small and the
/// error paths are tested once.
///
/// Deterministic: types sorted by name, props in catalog order, no
/// timestamps; output is formatted with `dart_style`, so two runs over the
/// same catalog are byte-identical.
library;

import 'package:dart_style/dart_style.dart';

import 'catalog.dart';

/// Generates the registry source for [catalog].
///
/// Provenance headers are parameterized from the catalog's name block —
/// nothing in the output hardcodes a package or catalog name.
String emitRegistry(Catalog catalog) {
  final buf = StringBuffer()
    ..writeln('// GENERATED — do not edit.')
    ..writeln('// ${dartProvenanceLine(catalog)}')
    ..writeln('//')
    ..writeln('// Typed factory registry: wire type name -> Seed factory.')
    ..writeln('// Construction-time validation (unknown type, missing or')
    ..writeln('// mistyped prop, unknown prop, children on a leaf) throws')
    ..writeln('// structured TaxonomyExceptions; nothing outside this file')
    ..writeln('// hardcodes component type names.')
    ..writeln();

  // Imports: package: imports first (genesis_taxonomy among them, sorted),
  // then relative imports, each block sorted.
  final imports = {
    'package:genesis_taxonomy/genesis_taxonomy.dart',
    for (final t in catalog.types) t.dart.import,
  }.toList()..sort();
  final packageImports = imports.where((i) => i.startsWith('package:'));
  final relativeImports = imports.where((i) => !i.startsWith('package:'));
  for (final i in packageImports) {
    buf.writeln("import '${_escape(i)}';");
  }
  if (relativeImports.isNotEmpty) {
    buf.writeln();
    for (final i in relativeImports) {
      buf.writeln("import '${_escape(i)}';");
    }
  }

  buf
    ..writeln()
    ..writeln(
      '/// Typed factory registry for catalog '
      "'${_escape(catalog.name)}' v${_escape(catalog.version)}.",
    )
    ..writeln('final ComponentRegistry componentRegistry = ComponentRegistry(')
    ..writeln("  catalogName: '${_escape(catalog.name)}',")
    ..writeln("  catalogVersion: '${_escape(catalog.version)}',")
    ..writeln('  entries: {');
  for (final type in catalog.types) {
    buf.writeln(_entrySource(type));
  }
  buf
    ..writeln('  },')
    ..writeln(');');

  return DartFormatter(
    languageVersion: DartFormatter.latestLanguageVersion,
  ).format(buf.toString());
}

/// The provenance line shared by both generated artifacts (seam 2).
String dartProvenanceLine(Catalog catalog) =>
    "Generated by genesis_taxonomy from catalog '${catalog.name}' "
    'v${catalog.version}.';

String _entrySource(CatalogType type) {
  final t = _escape(type.name);
  final knownProps = type.props.map((p) => "'${_escape(p.name)}'").join(', ');
  final buf = StringBuffer()
    ..writeln("    '$t': RegistryEntry(")
    ..writeln('      container: ${type.container},')
    ..writeln('      knownProps: const {$knownProps},')
    ..writeln('      build: (props, children, key) => ${type.dart.className}(');
  for (final propName in type.dart.positionalProps) {
    buf.writeln('        ${_propReader(type, propName)},');
  }
  for (final propName in type.dart.namedProps) {
    buf.writeln('        $propName: ${_propReader(type, propName)},');
  }
  if (type.container) {
    buf.writeln('        ${type.dart.childrenParam}: children,');
  }
  buf
    ..writeln('        key: key,')
    ..writeln('      ),')
    ..write('    ),');
  return buf.toString();
}

String _propReader(CatalogType type, String propName) {
  // The dart binding cover check (catalog parse) guarantees the prop exists.
  final prop = type.propNamed(propName)!;
  final t = _escape(type.name);
  final p = _escape(prop.name);
  final args = "'$t', props, '$p'";
  return switch (prop.type) {
    PropType.string =>
      prop.required
          ? 'Props.string($args)'
          : 'Props.stringOr($args, ${_stringLiteral(prop.defaultValue!)})',
    PropType.integer =>
      prop.required
          ? 'Props.integer($args)'
          : 'Props.integerOr($args, ${prop.defaultValue})',
    PropType.number =>
      prop.required
          ? 'Props.number($args)'
          : 'Props.numberOr($args, ${_doubleLiteral(prop.defaultValue!)})',
    PropType.boolean =>
      prop.required
          ? 'Props.boolean($args)'
          : 'Props.booleanOr($args, ${prop.defaultValue})',
    PropType.enumeration =>
      prop.required
          ? 'Props.enumeration($args, ${_enumLiteral(prop)})'
          : 'Props.enumerationOr($args, ${_enumLiteral(prop)}, '
                '${_stringLiteral(prop.defaultValue!)})',
  };
}

String _enumLiteral(CatalogProp prop) {
  final values = prop.enumValues!.map((v) => "'${_escape(v)}'").join(', ');
  return 'const [$values]';
}

String _stringLiteral(Object value) => "'${_escape(value as String)}'";

String _doubleLiteral(Object value) => '${(value as num).toDouble()}';

String _escape(String s) =>
    s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$');
